### ISSUE TITLE
Understanding and creating Solid vocabs

### ISSUE THREAD

**Issue by csarven** [solid/vocab#1]
Decide on whether to have a "core" vocabulary and the rest e.g., apps, server, ..?

Decide on whether to use a single or multiple namespace (depends on previous point).

**Comment by csarven** [comment]
Quoting @bblfish 's comment from [here](https://github.com/solid/solid-spec/issues/22#issue-73575701) b/c I think it describes the original intentions of this repository quite well:

>We need to have coherence in the ontologies we use so that our apps can work together . At the minimum we need to list the ontologies which apps are using, with perhaps descriptions of the problems found in those ontologies. This can help us choose interoperable ontologies. We should also document how different apps use them, so that we can start gathering patterns of deployment.

**Comment by dmitrizagidulin** [comment]
Closing this issue as too general. These questions (one vs many Solid related vocabularies, etc) will evolve during the course of the project.

**Comment by csarven** [comment]
The goal of this issue was to scope the purpose/intentions of this repo as opposed to addressing all of the details under a single issue.
