### ISSUE TITLE
consider ianarel:webmention instead of solid:inbox

### ISSUE THREAD

**Issue by elf-pavlik** [solid/vocab#12]
It seems that webmention link relaion will have canonical URI hosted by IANA
* https://github.com/aaronpk/webmention/pull/30
* https://github.com/mnot/I-D/issues/140

Maybe solid can use it instead of defining new term *inbox* ?

**Comment by csarven** [comment]
@elf-pavlik How do you see ianarel:webmention "equivalent" to solid:inbox?

What is the definition of `ianarel:webmention`? What is its domain/range?

**Comment by melvincarvalho** [comment]
thanks for the links and suggestion, but these two are different relations semantically, propose closing

**Comment by elf-pavlik** [comment]
> What is the definition of ianarel:webmention? What is its domain/range?
[solid:inbox has domain owl:Thing]
(https://github.com/solid/vocab/blob/master/solid-terms.ttl#L41), how does it differ from leaving it undefined? (i guess open world assumption)

> but these two are different relations semantically

where do you have more detailed specification of solid:inbox and solid:Inbox semantics?

i find 7 occurrences while searching for *inbox* in https://github.com/solid/solid-spec

**Comment by csarven** [comment]
What's written below is not necessarily in (dis)agreement with the Solid communities views. Just my own.

At the moment, the spec for inboxes is evolving / in discussion. The brief explanation (I think there is some consensus on this based on past discussions and implementation experience) is that a resource, e.g., a profile, document, has an inbox, which is a container/directory. An inbox contains notifications. We are trying to clarify the differences (if any) between the default inbox which is typically intended for a profile's inbox, and alternative inboxes (where any resource may have an inbox).

A notification is not necessarily a "mention" between two resources. A notification's contents can be (and most likely will be) application specific and may contain arbitrary information - you may want to think of it as a qualified relation but it is not strictly the case for all notifications.

I'm still interested in understanding why ianarel:webmention may be a suitable replacement for solid:inbox. First of all, can I dereference ianarel:webmention and get its definition in RDF? If not now, when?

I will create PRs for inbox/notifications soon.

**Comment by dmitrizagidulin** [comment]
@elf-pavlik - The `solid:Inbox` specs are located here, for the moment: https://github.com/solid/vocab/blob/master/solid-terms.ttl

**Comment by dmitrizagidulin** [comment]
But yeah, as @csarven mentioned, the Inbox semantics are still evolving.

**Comment by csarven** [comment]
@elf-pavlik I've noted that you've updated your comment re: `ianarel:webmention rdfs:subPropertyOf solid:inbox .` I think it would only be fair to consider that provided that:

1. The owner of ianarel ns declares that triple
2. `ianarel:webmention` definition is available

Otherwise, I'm not sure if there is much else to go on with here.

**Comment by elf-pavlik** [comment]
> 1. The owner of ianarel ns declares that triple
2. ianarel:webmention definition is available

Hopefully W3C will host RDF definitions of IANA link relations
https://gitter.im/solid/chat?at=56b0d93180ad69394a7bf5bf

**Comment by dmitrizagidulin** [comment]
See the Inbox spec proposal at [solid/PR #58](https://github.com/solid/solid/pull/58).

**Comment by csarven** [comment]
@elf-pavlik Are we okay to close this issue?
