### ISSUE TITLE
Add type registry related classes and properties

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/vocab#14]
The [type registry](https://github.com/solid/solid/blob/master/proposals/data-discovery.md) spec mentions the following new terms. 
Add them to the `solid-terms` vocabulary:
- `publicTypeIndex`
- `privateTypeIndex`
- `TypeIndex`
- `ListedDocument`
- `UnlistedDocument`
- `TypeRegistration`
- `instance`
- `instanceContainer`
- `forClass`

**Comment by dmitrizagidulin** [comment]
(I'm a bit unclear on how `solid:instance` is different from something like `ldp:RDFResource`..)

**Comment by dmitrizagidulin** [comment]
Updated the issue description to include adding two new terms, `publicTypeIndex` and `privateTypeIndex`

**Comment by dmitrizagidulin** [comment]
Updated to match https://github.com/solid/solid/pull/79

**Comment by elf-pavlik** [comment]
Please documen't well how `solid:ListedDocument` and `solid:UnlistedDocument` work

**Comment by csarven** [comment]
https://github.com/solid/vocab/commit/ddf5ac5a00f280cca02d1c1a38ee8441410106ad reflects this issue. I suggest closing this issue if deemed appropriate.
