### ISSUE TITLE
move vocab namespace to HTTPS

### ISSUE THREAD

**Issue by elf-pavlik** [solid/vocab#20]
currently: *http*://www.w3.org/ns/solid/terms#

should become: **https**://www.w3.org/ns/solid/terms#

**Comment by akuckartz** [comment]
:+1:

**Comment by RubenVerborgh** [comment]
Let's at least discuss while we still can. It's late, but not too late, and http has problems that https has not.

**Comment by melvincarvalho** [comment]
@RubenVerborgh you can consider this a formal objection.  Changing vocab name spaces breaks lots of stuff that is in use.  We have tons of http vocabs in solid, this is just one.

Discussion alone scares the living daylights out of me!

If in doubt, please seek resolution from Tim.

**Comment by megoth** [comment]
Well, both URLs are dereferencable, so I'm guessing we're not alone in mistakingly using one or the other... The case could be made that things are broken either way, and we should have a discussion pros and cons to conclude which one we want to continue with.

Are there any numbers at all on uses? I would guess those numbers are hard to come by and even harder to extrapolate usage outside of what is known. But if possible, I think any well-founded conclusion should take this into account.

The one big pro I see for keeping HTTP is that both protocols refer to HTTP as the base.

**Comment by melvincarvalho** [comment]
@megoth on the web http and https URIs are different name spaces

- When you change a URI, you can never completely tell who will have links to the old URI

- It is the the duty of a Webmaster to allocate URIs which you will be able to stand by in 2 years, in 20 years, in 200 years. This needs thought, and organization, and commitment

- This also causes frustration and reputational damage

see : https://www.w3.org/Provider/Style/URI

**Comment by elf-pavlik** [comment]
I wish it would have been addressed 2 years ago when I originally created this issue, and it would come less painful to change. I think it still should get some consideration and careful evaluation of pros and cons. I think in production people only use node-solid-server which could provide migration for the existing datasets. When it comes to apps (clients) I would like to see a list of maintained and actually working ones, this one here https://github.com/solid/solid-apps seems to have bunch of wrecked ships resting on the bottom of the see. In practice updating few maintained apps shouldn't take that much effort neither. IMO still possible to make that change without major pains.

**Comment by kjetilk** [comment]
What happens if a Web app tries to get a http-schema vocab and there is some kind of upgrade mechanism in place? Will it still refuse to do so?

**Comment by elf-pavlik** [comment]
I don't think that many applications will actually ever deference any of the IRIs denoting solid terms (actually at this point one gets github page with meaningless to machine HTML).
As I understand the challenge, HTTP IRI !== HTTPS IRI so any application which queries data relying on term defined in HTTP namespace. will simply not get expected result if statements use HTTPS namespace.
At the same times I think a handful applications relies on terms defined in solid namespace and changing it to HTTPS seems still quite manageable.

**Comment by melvincarvalho** [comment]
> HTTP IRI !== HTTPS IRI

Correct!  They must character match in order to be equivalent.

**Comment by kjetilk** [comment]
We discussed it, and @timbl has a plan, we need to apply some canonicalization to URI comparison. We should therefore keep the `http` schema. Patches very welcome, @melvincarvalho !

**Comment by csarven** [comment]
* https://datatracker.ietf.org/doc/html/rfc3986#section-6
* https://datatracker.ietf.org/doc/html/rfc7230#section-2.7.3
* https://github.com/solid/specification/issues/22
