### ISSUE TITLE
Quotas

### ISSUE THREAD

**Issue by kjetilk** [solid/vocab#29]
For the issue in https://github.com/solid/node-solid-server/issues/841 , which is urgent, we are discussing to add some RDF so that apps can use the data. 

I would prefer to use a datatype, so something like this:
```turtle
<#me> solid:nvmQuota "25"^^ex:megabyte .
```
but I have also considered the option of e.g.
```turtle
<#me> solid:nvmQuota [
  a solid:MaxQuota ;
  posix:size "25000000" .
].
```

**Comment by dmitrizagidulin** [comment]
I'd vote for the 1st one. The not requiring a bnode is a pretty big advantage (query wise)

**Comment by kjetilk** [comment]
Yeah, I would prefer the simplicity of the first one too. I think `posix:size` could be subpropertied ("verbing weirds language"! Not subclassed, BTW :-) ), but I still like the datatype...

**Comment by timbl** [comment]
I'd vote for 
```
<#me> solid:nvmQuota "25000000"^^ex:byte .
```

or better
```
<#me> solid:nvmQuota "25000000" .
```

**Comment by dmitrizagidulin** [comment]
(Wait, I thought we agreed that `storageQuota` was more understandable than `nvmQuota`?)

**Comment by kjetilk** [comment]
Yeah, it was something quickly said during a meeting.

I've done 
```turtle
<> solid:storageQuota "25000000" . 
```
(i.e., not the WebID, but the storage as subject).
