### ISSUE TITLE
Revert incorrect deprecation

### ISSUE THREAD

**Issue by melvincarvalho** [solid/vocab#30]
Had been on my todo list or quite a while.  

https://github.com/solid/vocab/commit/1cd827c0449f51c9d60920cb86027c3f991a5f7b

The following should be reverted, because

- the committer committed the change without creating a pull request
- the idea was to deprecate, and delete was done instead
- the term was still in use

after this has gone back in, we can have a proper conversation about process, and what we'd like to see here.  

cc @kjetilk @csarven

**Comment by RubenVerborgh** [comment]
Link to the issue that discusses deprecation?

**Comment by melvincarvalho** [comment]
@RubenVerborgh that's the point.  Committer just waded in without linking an issue or a PR.  Certainly there would have been objections otherwise.  

Unfortunately back then we didnt have a release manager or a process to prevent this.

**Comment by RubenVerborgh** [comment]
Not asking for a PR, looking for a pointer to "the idea was to deprecate" (did a search on this repo but missed it).

**Comment by melvincarvalho** [comment]
@RubenVerborgh was just discussed on gitter.  Im sure there's some chat logs.  But an issue is better.

**Comment by RubenVerborgh** [comment]
Yeah, let's have an issue to decide what needs to happen to solid:inbox, before we take any further action.

**Comment by melvincarvalho** [comment]
@RubenVerborgh yes, agreed, its my intention to replace the term until there is consensus.

**Comment by melvincarvalho** [comment]
I think two issues to discuss.

- A process surrounding vocabulary terms that may be in use

- What to do about this individual term

**Comment by kjetilk** [comment]
Mmm, seems like we need to have a process around use cases here, so that we understand how inboxes are used in Solid.

One thing that I felt was that "any resource could be an inbox, it is just a matter of backend processing", but I never entered into a discussion about it, so I'd like to see the use cases.

**Comment by melvincarvalho** [comment]
Quite a few use cases.  It is used in warp to show when you share a file (say a holiday snap), and in the inbox app to display your notifications.  I've used this feature a lot to share stories with other people using solid.

PS we should try and get those apps working with 5.0.0 (in oidc mode)

**Comment by melvincarvalho** [comment]
More important here is that we need a process regarding changes to vocabs.  Changes such as adding notices should require a pull request and a review to go through.  Deletion should never happen of terms in use (that's linked data 101).  @kjetilk could you help me set this up?

**Comment by melvincarvalho** [comment]
@justinwb I was also discussing an interesting use case with @kjetilk about adding a friend request.  One way this might be possible is to send a notification to an append only folder.  Possibly inbox, or possibly a special friend request folder is better (to prevent you searching potentially 100s of messages).  So possibly the notification class is useful here too.

**Comment by melvincarvalho** [comment]
This is all fixed now, aside from the process issues brought up.  Feel free to reopen if something is not addressed, or I think better, a new issue for future changes.

**Comment by RubenVerborgh** [comment]
> This is all fixed now,

Well, not really, we agreed we'd create an issue for it. And now there's again a commit without a PR on this matter.

> It is used in warp to show when you share a file (say a holiday snap), and in the inbox app to display your notifications

So these apps need to be upgraded?
Also, their functionality doesn't depend on the property existing in the ontology?

> I've used this feature a lot to share stories with other people using solid.

Story says the same, different URL.

I'll create the issues.

**Comment by melvincarvalho** [comment]
@RubenVerborgh well the apps use webid-tls which is not tested so much these days but was, say, last year.

Just getting back to a clean state, so we can use a better process.

Thanks for raising issues!
