### ISSUE TITLE
Discovering the application workspace

### ISSUE THREAD

**Issue by csarven** [solid/vocab#9]
(Putting `ws:masterWorkspace` aside) `ws:workspace` only leads to Workspaces, which would then require a second round of requests for all of the workspaces to discover the application workspace.

I think we need a specific property to help discover the application workspace (i.e., which is an instance of a `solid-app:PreferencesWorkspace` faster. It is sufficiently high profile that it deserves its own dedicated property.

```
ws:applicationWorkspace a rdf:Property ;
     :label "application workspace";
     :range ws:Workspace;
     #or :range solid-app:PreferencesWorkspace;
```

Example usage:
```
<http://example.org/> ws:applicationWorkspace <../Applications/> .

<../Applications/>
    a <http://www.w3.org/ns/solid/app#PreferencesWorkspace> ,
       <http://www.w3.org/ns/pim/space#PreferencesWorkspace> ,
       <http://www.w3.org/ns/pim/space#Workspace> ;
    <http://purl.org/dc/terms/title> "Applications preferences workspace" .
```

**Comment by dmitrizagidulin** [comment]
Design discussion in progress, see https://github.com/solid/solid/issues/23

**Comment by dmitrizagidulin** [comment]
No longer relevant, workspace concept deprecated.
Closing.
